name: CI/CD Pipeline

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies (optional but useful if you build locally too)
        run: dotnet restore backend/auth-service/auth-service.csproj

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker build -t caresoftchandana/caresoft/auth-service -f backend/auth-service/Dockerfile backend/auth-service
          docker build -t caresoftchandana/caresoft/user-service -f backend/user-service/Dockerfile backend/user-service

      - name: Push to Docker Hub
        run: |
          docker push caresoftchandana/caresoft/auth-service
          docker push caresoftchandana/caresoft/user-service

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: kubectl apply -f infrastructure/k8s/deployment.yaml
