name: CI/CD Pipeline

on:
  workflow_dispatch:  # This enables manual triggering from the GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker build -t caresoftchandana/caresoft/auth-service -f backend/auth-service/Dockerfile backend/auth-service
          docker build -t caresoftchandana/caresoft/user-service -f backend/user-service/Dockerfile backend/user-service

      - name: Push to Docker Hub
        run: |
          docker push caresoftchandana/caresoft/auth-service
          docker push caresoftchandana/caresoft/user-service

      - name: Deploy to Kubernetes
        run: kubectl apply -f infrastructure/k8s/deployment.yaml
