name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker images
        run: |
          docker build -t auth-service backend/auth-service
          docker build -t user-service backend/user-service
      - name: Push to Docker Hub
        run: |
          docker push your-docker-repo/auth-service
          docker push your-docker-repo/user-service
      - name: Deploy to Kubernetes
        run: kubectl apply -f infrastructure/k8s/deployment.yaml
